name: test action parameter-store
on:
  workflow_dispatch:
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

env:
  AWS_REGION : "us-east-1"
  
permissions:
  id-token: write  
  contents: write

jobs:
  parameter-store:
    name: parameter store
    needs: bump
    runs-on: [self-hosted, gmail]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::xxx:role/some_role
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Get Values From AWS Parameter Store
        uses: ./
        with:
          secrets: |
            /key | GITHUB_TOKEN
      
      - name: tag
        if: github.ref == 'refs/heads/main'
        run: |
          version=$(cat VERSION)
          major=$(cat VERSION| cut -d'.' -f1)    
          sed -i "s|action@v.*|action@v${major}|g" README.md
          
          git config --global user.name "CI Build"
          git config --global user.email "ci.build@gmail.com"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Versioning action v$major latest $version [skip ci]"
            git pull --rebase
            git push
          fi

          git tag v$major --force
          git tag v$version
          git push --tags --force
      
  